addpath('matlab');
vl_setupnn
if ispc

  cudnnRoot = 'C:\Program Files\NVIDIA GPU Computing Toolkit\cudnn-8.0-windows10-x64-v7\cuda';
  cudarootdir = 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0';
  vl_compilenn('enableGpu', true, ...
                 'cudaRoot', cudarootdir, ...
                 'cudnnRoot', cudnnRoot, ...
                 'cudaMethod', 'nvcc', ...
                 'enableCudnn', true, ...
                 'verbose', 1, ...
                 'debug', 0 ) ;
             
else            
  cudaArch  = [...
    '-gencode=arch=compute_35,code=\"sm_35,compute_35\" ' ...
    '-gencode=arch=compute_52,code=\"sm_52,compute_52\" '...
    '-gencode=arch=compute_61,code=\"sm_61,compute_61\"'];

  vl_compilenn('enableGpu', true, ...
                 'cudaRoot', '/usr/local/cuda-8.0', ...
                 'enableCudnn', true, ...
                 'cudnnRoot', '/usr/local/cuda-8.0','verbose',1, 'cudaArch',cudaArch);

end
